### ISSUE TITLE
Feedback zum Testat vom 23.4.2015

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-05#5]
Die Lösung erhält in Summe **81 Punkte**. Siehe folgendes Feedback.

### Positives
* JavaDoc ausreichend und ausführlich.
* Verwendung einer Konstanten für die Nachkommastelle.

##### Account: Kontostand redundant gespeichert (-5)
Das Führen des Kontostandes als eigene Variable ist fehleranfällig, da man leicht vergessen kann, bei einer Buchung die Variable mitzuführen. Besser ist den Kontostand aus den Buchung immer frisch zu berechnen. So ist es auch in professioneller Software üblich.
##### Account/Amount: De-Facto-Standard für den Aufbau von Java-Klassen nicht eingehalten (-7)
Die Reihenfolge der Bestandteile in einer Java-Klasse sollte Datenteil (Attribute) – Konstruktor – Methoden sein. Ist das nicht der Fall, wird das Erfassen einer unbekannten Klasse erschwert und der Inhalt schwer leserlich.
##### Currency: Doppelter Code (-2)
hasSubunit() fragt in einer if-Abfrage, ob subunit true ist und gibt dann true zurück. Das ist nicht notwendig, da subunit bereits boolean ist.
##### Amount: Vergleich zweier Objekte mit == (-5)
In add() und subtract() werden zwei Currency-Objekte mit „==“ verglichen. Das ist hier falsch, da „==“ prüft, ob die Referenz zweier Objekte gleich ist, also ob es sich um dasselbe Objekt handelt. Soll nur auf die Gleichheit von Objekten geprüft werden, wird equals() verwendet.

**Comment by KaroBee** [comment]
Hi, ich hab euch mal zusammengefasst, was ihr machen müsst, um exercise3 anzulegen. 1 und 2 habe ich gefixt :)
Siehe README2 in der Hauptübersicht.
VG. Euer Tutor

**Comment by Sena1** [comment]
Hey ok, vielen Dank :)
